apiVersion: 1

datasources:
  - name: CrateDB (QuantumLeap)
    uid: cratedb
    type: grafana-postgresql-datasource
    access: proxy
    url: cratedb:5432
    user: crate
    jsonData:
      database: doc
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
