apiVersion: 1

datasources:
  - name: FIWARE PostgreSQL
    uid: fiware-postgres
    type: postgres
    access: proxy
    url: ${FIWARE_PG_HOST}:${FIWARE_PG_PORT}
    user: ${FIWARE_PG_USER}
    secureJsonData:
      password: ${FIWARE_PG_PASSWORD}
    jsonData:
      database: ${FIWARE_PG_DATABASE}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
